defaults:
  - base

net:
  conv:
    _target_: src.models.layer.gconconv.GCONLayer
    dim_in: ${model.net.dim_inner}
    dim_out: ${model.net.dim_inner}
    channel_list: [[0], [1], [2], [4], [0, 1], [1, 2], [2, 4]]
    combine_fn: 'att_bias'
    num_heads: 1
    activation_att1: 'elu'
    activation_att2: 'elu'
    activation: 'elu'
    depth_mlp: 1
    skip: True
    add_self_loops: True
    norm: 'gcn'
    filter_norm_dim: None
    bias: False
