# @package _global_

data:
  task: 'maxclique'

model:
  task: 'maxclique'

  optimizer:
    _target_: torch.optim.AdamW
    lr: 0.001
    weight_decay: 0.0

  criterion:
    _target_: src.models.loss.copt_loss.maxclique_loss_pyg
    _partial_: True
    alpha: 1.0
    beta: 1.01
    reduction: 'sum'

  metrics:
    size:
      _target_: src.utils.metrics.maxclique_size_pyg
      _partial_: True
      dec_length: 300
      num_seeds: 10
