# @package _global_

data:
  task: 'mds'

model:
  task: 'mds'

  criterion:
    _target_: src.models.loss.copt_loss.mds_loss_pyg
    _partial_: True
    beta: 1.0
    reduction: 'sum'

  metrics:
    size:
      _target_: src.utils.metrics.mds_size_pyg_parallel
      _partial_: True
      num_seeds: 10

callbacks:
  model_checkpoint:
    mode: 'min'
  early_stopping:
    mode: 'min'